version: '3'

services:

  postgres:
    image: postgres:9
    container_name: shopify_test_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
    ports:
      - '5432:5432'
    volumes:
      - shopify_test-postgres:/var/lib/postgresql/data

  redis:
    container_name: shopify_test_redis
    image: redis:4
    ports:
      - '6379:6379'
    volumes:
      - shopify_test-redis:/var/lib/redis/data

  box:
    image: busybox
    container_name: shopify_test_box
    volumes:
      - /shopify_test-box

  app:
    container_name: shopify_test_app
    build: .
    command: ./start.sh
    volumes:
      - .:/shopify_test
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
      - box
    env_file:
      - .env

  sidekiq:
    container_name: shopify_test_sidekiq
    build: .
    command: sidekiq -C config/sidekiq.yml
    restart: always
    env_file:
      - .env
    depends_on:
      - app

volumes:

  shopify_test-postgres:
  shopify_test-redis:
  shopify_test-box:
