default: &default
  secret_key_base: 522ac5c230edcceee56968a8c9840da1ee9caf0fab1f7bab7ace2a2cf6e01fe52352e41ec08819a898a7106ef0893ad57d505526580aea0eb5e20f4fc62a8dcc

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
