default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  shopify:
    api_key: <%= ENV["SHOPIFY_API_KEY"] %>
    secret: <%= ENV["SHOPIFY_SECRET"] %>
  redis:
    url: <%= ENV["REDIS_URL"] %>
    namespace: <%= ENV["REDIS_NAMESPACE"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
