default: &default
  shopify:
    api_key: <%= ENV["SHOPIFY_API_KEY"] %>
    secret: <%= ENV["SHOPIFY_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
